### ISSUE TITLE
Refactor code for Pokemon type

### ISSUE THREAD

**Issue by bhavin-a** [Juggernaut9/pokemon#13]
Hi @Juggernaut9 

Currently, to match Pokemon type, we are using a function and branching it with `if else` statements. Instead of branching, I think we can use a constant with an idea of utilising it as a hashmap. Much lesser cognitive complexity and easier to maintain :).

Please let me know if you find this ok. I can do a small tweak with the code. Thanks!

**Comment by BhavyaCodes** [comment]
yes please go ahead!

**Comment by bhavin-a** [comment]
Cool! Can you please assign it to me as well? Thanks again

**Comment by secretshardul** [comment]
Done. @Juggernaut9 check out my PR #26
