### ISSUE TITLE
Add Header

### ISSUE THREAD

**Issue by BhavyaCodes** [Juggernaut9/pokemon#2]
Add a Header. make it beautiful :)

**Comment by haseeb1009** [comment]
@Juggernaut9  Can you assign this issue to me so that I can work on it?

**Comment by chinmaikaveti2001** [comment]
hi! sir can u please assign this issue to me..?
I want to work on this issue....

**Comment by haseeb1009** [comment]
@Juggernaut9  Do you need any buttons in the header?

**Comment by haseeb1009** [comment]
Opened a PR to fix this issue, will also add search feature after this PR is merged

**Comment by BhavyaCodes** [comment]
merged your PR @haseeb1009 , i'll be creating a new issue about the search feature, please check it, I'll assign it to you
