### ISSUE TITLE
Search Pokemon

### ISSUE THREAD

**Issue by BhavyaCodes** [Juggernaut9/pokemon#27]
- Pokemon Should be searchable using api and NOT from pokemon.json
 - results should be shown on a different component and use react-router-dom to display on a separate page, path can /pokemon/pokemonName or /pokemon/pokemonId, I'll leave that you
 - There must be a back button on this page

**Comment by BhavyaCodes** [comment]
@haseeb1009

**Comment by mcastre** [comment]
@Juggernaut9 i can take this one. Is there an existing api endpoint to call?

**Comment by daniel-donateli** [comment]
@mcastre look for it at https://pokeapi.co/

**Comment by BhavyaCodes** [comment]
Hey @daniel-donateli , @mcastre , on pull request https://github.com/Juggernaut9/pokemon/pull/23 @haseeb1009  said he will fix this issue, Im unable to assign it to him I think he needs to comment here for me to be able to assign him

**Comment by haseeb1009** [comment]
@Juggernaut9  Thanks for creating the issue, please assign it to me

**Comment by BhavyaCodes** [comment]
done 👍
