### ISSUE TITLE
add footer

### ISSUE THREAD

**Issue by BhavyaCodes** [Juggernaut9/pokemon#3]
make the website bootiful

**Comment by RidhikGovind** [comment]
Hey @Juggernaut9  can I work on this ? If yes, do assign this task to me and can I hear out any ideas of yours to make it 'bootiful' ?

**Comment by SagarGi** [comment]
Hey can I try this i am new to it

**Comment by Rishav0907** [comment]
Can I work on this?

**Comment by BhavyaCodes** [comment]
sorry for late reply Im assigning this task to @RidhikGovind . let me know if you can do it :)

**Comment by RidhikGovind** [comment]
@Juggernaut9 I will work on this !

**Comment by SagarGi** [comment]
Yes i would like to work on it if you allow me 😀😀

**Comment by BhavyaCodes** [comment]
footer has been added, if you'd like to make any changes then feel free to send pr @everyone
