### ISSUE TITLE
Sorted Pokemons

### ISSUE THREAD

**Issue by daniel-donateli** [Juggernaut9/pokemon#31]
Make CardList component return PokeCards ordered by pokemon id

**Comment by bhavin-a** [comment]
Hi @daniel-donateli 

Can I give this issue a try? If possible, can you please assign it to me? Thanks!

**Comment by daniel-donateli** [comment]
Sure but @Juggernaut9 is the one who can assign you

**Comment by BhavyaCodes** [comment]
@Bhavin789 go for it

**Comment by bhavin-a** [comment]
Sure @Juggernaut9 , thanks!

**Comment by BhavyaCodes** [comment]
fixed with https://github.com/Juggernaut9/pokemon/pull/35 by @Bhavin789 , closing this issue, thank you all
